### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Anupam-dagar** [GeekHaven/Pragma#10]
- [x] The arrow button is not visible in mobile, do something for that 
- [x] Look for minor text aligment issues in mobile view 
- [x] When the navbar becomes white as we scroll down, the logos should be replaced by a thick heading 'SDC', link="#home"
- [x] Fix landing page scroll (content remains fixed everything else scrolls).
- [x] Reduce margins from left and right sides.
- [x] Fix landing page image.
- [ ] Remove white space between 2 sections.
--
- [x] Add a sponsor section
- [x] Add a footer
- [ ] Change design of schedule cards (discuss in group first)
- [ ] animate svg's
